name: space_time
description: "A modern clock app with multiple features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  file_picker: ^10.1.2
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8
  vibration: ^2.0.1
  timezone: ^0.9.4
  async: ^2.11.0
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
    
    - assets/images/3.jpeg
    - assets/images/3.ico
    - assets/sounds/childhood.wav
    - assets/sounds/morning.wav
    - assets/sounds/over_the_horizon_2012.mp3
    - assets/sounds/over_the_horizon_17.mp3
    - assets/sounds/melody.wav
    - assets/sounds/timer_end.wav
    - assets/images/Pre-Available_Wallpapers/wallpaper1.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper2.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper3.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper4.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper5.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper6.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper7.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper8.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper9.jpg
    - assets/images/Pre-Available_Wallpapers/wallpaper10.jpg